---
- name: Install Apache and Upload my Web Page
  hosts: all
  become: yes

  vars:
    source_file: /home/ubuntu/web/dz11/index.html
    destin_file: /var/www/html


  tasks:

  - name: Check and print Linux Version
    debug: var=ansible_os_family

  - name: Install Apache Web Server for Debian
    apt: name=apache2 state=latest
    when: ansible_os_family == "Debian"

  - name: Install Apache Web Server for RedHat
    yum: name=httpd state=latest
    when: ansible_os_family == "RedHat"


  - name: Copy MyHomePage to servers
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
#   notify: Restart Apache

  - name: Start Web Server service for RedHat
    service: name=httpd state=started enabled=yes


      
  handlers:
  - name: Restart Apache Debian
    service: name=apache2 state=restarted


  - name: Restart RedHat
    service: name=httpd state=restarted

