---
- name: Install Apache and Upload my Web Page
  hosts: all
  become: yes

  vars:
    source_file: /home/ubuntu/web/dz11/index.html
    destin_file: /var/www/html


  tasks:
  - name: Install Apache Web Server
    apt: name=apache2 state=latest

  - name: Copy MyHomePage to servers
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache


      
  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted


