---
- name: My PB-TaskDelegateTo
  hosts: all
  become: yes

  vars:
    mytext: "Hi bro, i'm working"

  tasks:
   - name: Ping test
     ping:

   - name: Unregister Server from Load Balancer
     shell: echo This server {{ inventory_hostname }} was deregistred from our Load Balencer, node name is {{ ansible_nodename }} >> /home/log.txt
     delegate_to: 127.0.0.1  # Этот task выполниться только на localhost. 

   - name: Create file1
     copy:
       dest: /home/file1.txt
       content: |
         This is file1
         Is my "var" working now?
         {{ mytext }}
     delegate_to: Linux3


   - name: Create file2
     copy:
       dest: /home/file2.txt
       content: |
         This is file2
         Is my "var" working now?
         {{ mytext }}
 
   - name: Reboot my servers
     shell: sleep3 && reboot now
     async: 1
     poll: 0

   - name: Wait till my server will come up online
     wait_for: #  Чего я жду чтоб запустить task
       host: "{{ inventory_hostname }}"
       state: started
       delay: 5 # Начнет ждать через 5 сек.
       timeout: 40 # Ждать максимум времени 40 сек.
     delegate_to: 127.0.0.1       
 


