---
- name: Loops Playbook
  hosts: Linux3
  become: yes

  tasks:

  - name: Say Hello to All
    debug: msg="Hello {{item}}" # Item принимает loop , debug var: ...  выводит сообщение.  msg= "...{{...}}" вывод переменной. 
    loop:
      - "Jeka"
      - "Vasgen"
      - "Alena"
      - "Masha"

  - name: Loop Until example
    shell: echo -n W >> newfile.txt && cat newfile.txt
    register: output  # Результат записываю в output
    delay: 3 #  Задержка между выполнением команд 3 сек.
    retries: 10 #Сколько раз повторить (по дефолту 3 раза).
    until: output.stdout.find("WWWWW") == false # Продолжает запускать команду пока в файле не будет WWWWW.


  - name: Print Final Output
    debug:
      var: output.stdout


#  - name: Install many packages
#    apt: name={{ item }} state=latest
#    loop:
#      - pyton 
#      - htop
#      - tree
